Repository sebrock/bananominer-watch-DEV_TEST, pull requests merged in 2020-07, with the labels that each got.

#29 Added vietnamese translations
  _locales/vt/message.json
Labels: enhancement, localization

#33 Added locale for es_419
  _locales/es_419/messages.json
Labels: localization

#35 Feature/verify active homefold
  _locales/no/messages.json
  scripts/components/renderUser/checkWus.js
  scripts/components/renderUser/fetchBananoMiner.js
Labels: enhancement, localization

#37 _locale no_norwegian fix
  _locales/no/messages.json
Labels: bug, localization

#38 Version 1.3.0
  _locales/da/messages.json
  _locales/de/messages.json
  _locales/hi/messages.json
  _locales/no/messages.json
  assets/store.png
  banano.css
  banano.html
  changelog.md
  manifest.json
  scripts/components/helper/estimateBan.js
  scripts/components/helper/querySelectors.js
  scripts/components/renderTop/index.js
  scripts/components/renderUser/checkWus.js
  scripts/components/renderUser/fetchBananoMiner.js
  scripts/index.js
Labels: enhancement, localization, release
