Repository sebrock/bananominer-watch-DEV_TEST, pull requests merged in 2021-03, with the labels that each got.

#64 Update cors url
  scripts/components/renderUser/fetchBananoMiner.js
Labels: bug

#66 Add ban conversion to usd
  scripts/components/renderUser/fetchBananoMiner.js
Labels: enhancement

#68 Add active clients count
  _locales/en/messages.json
  _locales/fil/messages.json
  banano.css
  scripts/components/renderUser/fetchBananoMiner.js
Labels: enhancement, i18n, localization

#70 Feature/chart bananominer
  banano.css
  banano.html
  charts.html
  manifest.json
  scripts/components/renderChart/index.js
  scripts/components/renderUser/checkWus.js
  scripts/components/renderUser/fetchBananoMiner.js
  scripts/components/renderUser/footerMenu.js
  scripts/index.js
Labels: enhancement
